language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - EMULATOR_API_LEVEL=27
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator


script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
  - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)