language: android
jdk: oraclejdk10.0.2
# Global Reference Values for the file
env:
  global:

  - ANDROID_API_LEVEL=28
  - EMULATOR_API_LEVEL=27
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

  before_script:
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - ./gradlew connectedCheck
  - ./gradlew test

  after_success:
  - bash <(curl -s https://codecov.io/bash)